# Generated by Django 4.2 on 2025-04-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0021_seed_audio_metadata'),
        ('data_models', '0031_alter_deployment_fields'),
    ]

    operations = [
    ]
